language: php
php:
  - '7.2'
  - '7.3'
script:
  - composer install
  - npm install
  - npm run dev
  - ./bin/phpunit
  - ./bin/phpunit --coverage-clover=coverage.xml
  - bash <(curl -s https://codecov.io/bash)